name: flutter_paystack
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 1.0.4+1
author: Wilberforce Uwadiegwu <faradaywilly@gmail.com>
homepage: https://github.com/wilburt/flutter_paystack

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  intl: ^0.16.1
  meta: ^1.1.8
  async: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.8
  mockito: ^4.1.1


flutter:
  plugin:
    platforms:
      android:
        package: co.paystack.flutterpaystack
        pluginClass:  FlutterPaystackPlugin
      ios:
        pluginClass:  FlutterPaystackPlugin

  assets:
   - assets/images/



environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.20.1 <2.0.0"