name: flutter_paystack
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 0.9.0
author: Wilberforce Uwadiegwu <faradaywilly@gmail.com>
homepage: https://github.com/wilburt/flutter_paystack

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+16
  intl: ^0.15.7
  meta: ^1.1.5

flutter:
  plugin:
    androidPackage: co.paystack.flutterpaystack
    pluginClass: FlutterPaystackPlugin

  assets:
   - assets/images/visa.png
   - assets/images/jcb.png
   - assets/images/verve.png
   - assets/images/discover.png
   - assets/images/american_express.png
   - assets/images/dinners_club.png
   - assets/images/mastercard.png
   - assets/images/paystack_logo.png
   - assets/images/successful.png
   - assets/images/otp.png
   - assets/images/dob.png



environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"
  flutter: ">=0.5.1 <2.0.0"